#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar  6 16:44:38 2019

@author: mahparsa
"""
#sourse code can be found https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve.html#scipy.signal.convolve
#this code is shows how a filter can smooth a signal. 
from scipy import signal
sig = np.repeat([0., 2., 0.], 400)
#signal.hann(M, sym=True) is used to generate a Hann window.
#for more information, you can refer to the following page.
#The window is known as the Cosine Bell or the “Hanning” window. 
#https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.signal.hann.html
win = signal.hann(100)
filtered = signal.convolve(sig, win, mode='same') / sum(win)
import matplotlib.pyplot as plt
fig, (ax_orig, ax_win, ax_filt) = plt.subplots(3, 1, sharex=True)
ax_orig.plot(sig)
ax_orig.set_title('The original signal')
ax_orig.margins(0, 0.1)
ax_win.plot(win)
ax_win.set_title('Filter impulse response')
ax_win.margins(0, 0.1)
ax_filt.plot(filtered)
ax_filt.set_title('Filtered signal')
ax_filt.margins(0, 0.1)
fig.tight_layout()
fig.show()
